config/routes.rb
Rails.application.routes.draw do
  resources :hesis
  devise_for :users
  resources :students
  resources :advisors
  resources :programs

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root :to => "hesis#index"
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :program
  belongs_to :advisor
  has_many :hesis

  enum attempt_number: {
    "1st attempt" => 0,
    "Retake for higher score" => 1,
    "Retake:All" => 2,
    "Retake:Math" => 3,
    "Retake:Math+Vocab" => 4,
    "Retake:Math+Reading" => 5,
    "Retake:Reading+Vocab" => 6
  }
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show create edit update destroy ]
  before_action :ensure_no_more_than_10_testers, only: %i[ create update]

  # GET /students or /students.json
  def index
    if params[:query].present?
      @students = Student.where("name iLIKE ?", "%#{params[:query]}%")
    else
      @students = Student.all.order(:created_at)
    end
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to students_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to students_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:phone] && params[:name] || params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :program_id, :start_date, :advisor_id, :sle, :phone, :attempt_number, :hesi_date, :hesi_time)
    end

    def set_hesi
      @hesi = Hesi.where(date: student_params[:hesi_date], time: student_params[:hesi_time]) || Hesi.new(student_params[:hesi_date], student_params[:hesi_time])
    end

    def ensure_no_more_than_10_testers
      testers = Student.where(hesi_date: student_params[:hesi_date], hesi_time: student_params[:hesi_time])
      unless testers.size < 10
        render :new, status: :unprocessable_entity, notice: "That testing time is already full"
      end
    end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, class: "contents") do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :program_id %>
    <%= form.collection_select :program_id, Program.all, :id, :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :start_date %>
    <%= form.select :start_date, Program.start_dates.keys,  class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :advisor_id %>
    <%= form.collection_select :advisor_id, Advisor.all, :id, :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :sle %>
    <%= form.number_field :sle, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :attempt_number %>
    <%= form.select :attempt_number, Student.attempt_numbers.keys, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :hesi_date %>
    <%= form.date_field :hesi_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 " %>
  </div>

  <div class="my-5">
    <%= form.label :hesi_time %>
    <%= form.select :hesi_time, Hesi.test_times, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= student.name %>
  </p>

  <p class="my-5">
    <strong class="inline-block  font-medium mb-1">Program:</strong>
    <%= student.program.full_name %>
  </p>

  <p class="my-5">
    <strong class="inline-block font-medium mb-1">Start date:</strong>
    <%= Program.start_dates.keys[student.start_date] %>
  </p>

  <p class="my-5">
    <strong class="inline-block font-medium mb-1">Advisor:</strong>
    <%= student.advisor.name %>
  </p>

  <p class="my-5">
    <strong class="inline-block font-medium mb-1">Sle:</strong>
    <%= student.sle %>
  </p>

  <p class="my-5">
    <strong class="inline-block font-medium mb-1">Phone:</strong>
    <%= student.phone %>
  </p>

  <p class="my-5">
    <strong class="inline-block font-medium mb-1">Attempt number:</strong>
    <%= student.attempt_number %>
  </p>

  <p class="my-5">
    <strong class="inline-block font-medium mb-1">Hesi date:</strong>
    <%= student.hesi_date %>
  </p>

  <p class="my-5">
    <strong class="inline-block font-medium mb-1">Hesi time:</strong>
    <%= Hesi.test_times.keys[student.hesi_time] %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this student", student, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this student', edit_student_path(student), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/students/_students.html.erb
<!-- component -->
<%= turbo_frame_tag "students" do %>
<div class="flex flex-col h-screen">
    <div class="flex-grow overflow-auto">
      <table class="relative w-full border">
        <thead>
          <tr>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Student name</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Advisor</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Program</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Wonderlic Score</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Phone Number</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Hesi Date</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Hesi Time</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300"></th>
          </tr>
        </thead>
        <tbody class="divide-y bg-blue-100">
<%= cache do %>
  <% @students.each do |student| %>
          <tr>
            <td><%= link_to student.name, student_path(student), class: "px-6 py-4 text-center" %></td>
            <td><%= link_to student.advisor.name, advisor_path(student.advisor), class: "px-6 py-4 text-center"%></td>
            <td><%= link_to student.program.name, program_path(student.program), class: "px-6 py-4 text-center" %></td>
            <td class="px-6 py-4 text-center"><%= student.sle %></td>
            <td class="px-6 py-4 text-center"><%= student.phone %></td>
            <td class="px-6 py-4 text-center"><%= student.attempt_number %></td>
            <td class="px-6 py-4 text-center"><%= student.hesi_date %></td>
            <td class="px-6 py-4 text-center"><%= Hesi.test_times.keys[student.hesi_time] %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <% end %>
  </div>
<% end %>

app/views/students/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing student</h1>

  <%= render "form", student: @student %>

  <%= link_to "Show this student", @student, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to students", students_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/students/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Students</h1>
    <%= form_with(url: students_path, method: :get, data: {turbo_frame: "students"}) do |form| %>
      <%= form.label :query, "Search by name", class: "block mb-2" %>
       <div class="flex space-x-3">

          <%= form.text_field :query, class: "py-3 px-4 rounded border ring-0 focus:ring-4 focus:ring-blue-600 focus:shadow-none focus:border-blue-300 focus:outline-none" %>
          <%= form.submit "Search", class: "px-4 py-3 font-medium bg-blue-600 text-neutral-900 rounded inline-flex items-center cursor-pointer hover:bg-grey-400 focus:ring-4 ring-0 focus:ring-blue-100" %>

       </div>
    <% end %>
    <%= link_to 'New student', new_student_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="students" class="min-w-full">
    <%= render partial: 'students', students: @students %>
  </div>
</div>

app/views/students/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New student</h1>

  <%= render "form", student: @student %>

  <%= link_to 'Back to students', students_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/students/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @student %>

    <%= link_to 'Edit this student', edit_student_path(@student), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this student', student_path(@student), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to students', students_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>