config/routes.rb
Rails.application.routes.draw do
  resources :hesis
  devise_for :users
  resources :students
  resources :advisors
  resources :programs

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root :to => "hesis#index"
end

app/models/hesi.rb
class Hesi < ApplicationRecord

  has_many :students

  WEEK_DAYS = ['Sunday','Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

  def self.times_for_day
    {
      'Monday' => ['10:00am'],
      'Tuesday' => ['9:00am', '4:00pm'],
      'Wednesday' => ['9:00am', '1:00pm'],
      'Thursday' => ['9:00am', '1:00pm'],
      'Friday' => ['9:00am'],
      'Saturday' => ['9:00am']
    }
  end

  def self.student_count(date,time)
    Student.where(hesi_date: date, hesi_time: self.test_times[time]).count
  end

  def self.day_of_week(date)
    WEEK_DAYS[date.wday]
  end

  def self.date(date)
    date.to_fs(:long_ordinal)
  end


  def self.future_hesi_dates
    hesi_dates = Student.where(hesi_date: 0.day.ago..Float::INFINITY).distinct.pluck(:hesi_date).sort
  end

  def self.past_hesi_dates
    hesi_dates = Student.where('hesi_date < ?', Date.today).distinct.pluck(:hesi_date).sort
  end
  def self.testers_for_date_and_time(date, time)
    Student.where(hesi_date: date, hesi_time: time)
  end


  enum test_time: {
    "9:00am" => 0,
    "10:00am" => 1,
    "1:00pm" => 2,
    "4:00pm" => 3
  }
end

app/controllers/hesis_controller.rb
class HesisController < ApplicationController
  before_action :set_hesi, only: %i[ show edit update destroy ]
  before_action :set_students, only: %i[ create show edit update destroy]
# GET /hesis or /hesis.json
  def index
    @hesis = Hesi.all
  end

  # GET /hesis/1 or /hesis/1.json
  def show
  end

  # GET /hesis/new
  def new
    @hesi = Hesi.new

    @hesi.students.build
  end

  # GET /hesis/1/edit
  def edit
  end

  # POST /hesis or /hesis.json
  def create
    @hesi = Hesi.new(hesi_params)

    respond_to do |format|
      if @hesi.save
        format.html { redirect_to hesi_url(@hesi), notice: "Hesi was successfully created." }
        format.json { render :show, status: :created, location: @hesi }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hesi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hesis/1 or /hesis/1.json
  def update
    respond_to do |format|
      if @hesi.update(hesi_params)
        format.html { redirect_to hesi_url(@hesi), notice: "Hesi was successfully updated." }
        format.json { render :show, status: :ok, location: @hesi }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hesi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hesis/1 or /hesis/1.json
  def destroy
    @hesi.destroy

    respond_to do |format|
      format.html { redirect_to hesis_url, notice: "Hesi was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hesi
      @hesi = Hesi.find(:id)
    end

    # Only allow a list of trusted parameters through.
    def hesi_params
      params.require(:hesi).permit(:date, :time)
    end

    def set_students
      @students = Student.where(hesi_date: self.date, hesi_time: self.time )
    end 
end

app/helpers/hesis_helper.rb
module HesisHelper
end

app/views/hesis/_all_hesis.html.erb
<% Hesi.all_hesi_dates.each do |date| %>
  <h1><strong><%= "#{Hesi::WEEK_DAYS[date.wday]}, #{ date.to_fs(:long_ordinal) }" %></strong></h1>
  <% Hesi.times_for_day[Hesi::WEEK_DAYS[date.wday]].each do |time| %>
    <h2><%= time %></h2>
<div class="flex flex-col">
    <div class="pb-5">
      <table class="relative w-full border">
        <thead>
          <tr>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Student name</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Advisor</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Program</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Wonderlic Score</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">phone number</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Attempt Number</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300"></th>
          </tr>
        </thead>
        <tbody class="divide-y bg-blue-100">

        <% Hesi.testers_for_date_and_time(date, Hesi.test_times[time]).each do |student| %>
          <tr>
            <td class="px-6 py-4 text-center"><%= link_to student.name, student_path(student) %></td>
            <td class="px-6 py-4 text-center"><%= link_to student.advisor.name, advisor_path(student.advisor) %> </td>
            <td class="px-6 py-4 text-center"><%= link_to student.program.name, program_path(student.program) %></td>
            <td class="px-6 py-4 text-center"><%= student.sle %></td>
            <td class="px-6 py-4 text-center"><%= student.phone %></td>
            <td class="px-6 py-4 text-center"><%= student.attempt_number %></td>
            <td class="px-6 py-4 text-center"><%= button_to student.confirm,
              method: POST %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
   </div>
 </div>

<% end %>
<% end %>

app/views/hesis/_future_hesis.html.erb
<% Hesi.future_hesi_dates.each do |date| %>
  <h1><strong><%= "#{Hesi.day_of_week(date)}, #{ Hesi.date(date) }" %></strong></h1>
  <% Hesi.times_for_day[Hesi.day_of_week(date)].each do |time| %>
    <div class="relative flex h-16 items-center justify-between">
      <h2 class="inline-flex items-center justify-center "><strong><%= time %></strong></h2>
      <h3 class="clear-right">Count: <%= Hesi.student_count(date, time) %></h3>
    </div>
<div class="flex flex-col">
    <div class="pb-10">
      <table class="relative w-full border">
        <thead>
          <tr>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-600">Student name</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-600">Advisor</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-600">Program</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-600">Start Date</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-600">Wonderlic Score</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-600">phone number</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-600">Attempt Number</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-600"></th>
          </tr>
        </thead>
        <tbody class="divide-y bg-blue-100">

        <% Hesi.testers_for_date_and_time(date, Hesi.test_times[time]).each do |student| %>
          <tr>
            <td class="px-6 py-4 text-center underline"><%= link_to student.name, student_path(student) %></td>
            <td class="px-6 py-4 text-center underline"><%= link_to student.advisor.name, advisor_path(student.advisor) %> </td>
            <td class="px-6 py-4 text-center underline"><%= link_to student.program.name, program_path(student.program) %></td>
            <td class="px-6 py-4 text-center "><%= Program.start_dates.keys[student.start_date] %></td>
            <td class="px-6 py-4 text-center"><%= student.sle %></td>
            <td class="px-6 py-4 text-center"><%= student.phone %></td>
            <td class="px-6 py-4 text-center"><%= student.attempt_number %></td>
            <td class="px-6 py-4 text-center text-lg underline text-blue-600"><%= link_to "Reschedule", edit_student_url(student)  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
   </div>
 </div>

<% end %>
<% end %>

app/views/hesis/_hesi.html.erb
<div id="<%= dom_id hesi %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Date:</strong>
    <%= hesi.date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Time:</strong>
    <%= hesi.time %>
  </p>

   <h1><strong><%= "#{Hesi.day_of_week(hesi.date)}, #{ Hesi.date(hesi.date) }" %></strong></h1>
  <% Hesi.times_for_day[Hesi.day_of_week(hesi.date)].each do |time| %>
    <div class="relative flex h-16 items-center justify-between">
      <h2 class="inline-flex items-center justify-center "><strong><%= hesi.time %></strong></h2>
      <h3 class="clear-right">Count: <%= Hesi.student_count(hesi.date, hesi.time) %></h3>
    </div>
<div class="flex flex-col">
    <div class="pb-10">
      <table class="relative w-full border">
        <thead>
          <tr>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-600">Student name</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-600">Advisor</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-600">Program</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-600">Start Date</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-600">Wonderlic Score</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-600">phone number</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-600">Attempt Number</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-600"></th>
          </tr>
        </thead>
        <tbody class="divide-y bg-blue-100">

        <% Hesi.testers_for_date_and_time(hesi.date, Hesi.test_times[hesi.time]).each do |student| %>
          <tr>
            <td class="px-6 py-4 text-center underline"><%= link_to student.name, student_path(student) %></td>
            <td class="px-6 py-4 text-center underline"><%= link_to student.advisor.name, advisor_path(student.advisor) %> </td>
            <td class="px-6 py-4 text-center underline"><%= link_to student.program.name, program_path(student.program) %></td>
            <td class="px-6 py-4 text-center "><%= Program.start_dates.keys[student.start_date] %></td>
            <td class="px-6 py-4 text-center"><%= student.sle %></td>
            <td class="px-6 py-4 text-center"><%= student.phone %></td>
            <td class="px-6 py-4 text-center"><%= student.attempt_number %></td>
            <td class="px-6 py-4 text-center text-lg underline text-blue-600"><%= link_to "Reschedule", edit_student_url(student)  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
   </div>
 </div>

<% end %>

  <% if action_name != "show" %>
    <%= link_to "Show this hesi", hesi, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this hesi', edit_hesi_path(hesi), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/hesis/_past_hesis.html.erb
<% Hesi.past_hesi_dates.each do |date| %>
  <h1><strong><%= "#{Hesi.day_of_week(date)}, #{ Hesi.date(date) }" %></strong></h1>
  <% Hesi.times_for_day[Hesi.day_of_week(date)].each do |time| %>
    <div class="relative flex h-16 items-center justify-between">
    <h2 class="inline-flex items-center justify-center "><strong><%= time %></strong></h2>
    <h3 class="clear-right"><%= Hesi.student_count(date, time) %></h3>
    </div>
<div class="flex flex-col">
    <div class="pb-10">
      <table class="relative w-full border">
        <thead>
          <tr>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Student name</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Advisor</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Program</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Wonderlic Score</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">phone number</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Attempt Number</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300"></th>
          </tr>
        </thead>
        <tbody class="divide-y bg-blue-100">

        <% Hesi.testers_for_date_and_time(date, Hesi.test_times[time]).each do |student| %>
          <tr>
            <td class="px-6 py-4 text-center"><%= link_to student.name, student_path(student) %></td>
            <td class="px-6 py-4 text-center"><%= link_to student.advisor.name, advisor_path(student.advisor) %> </td>
            <td class="px-6 py-4 text-center"><%= link_to student.program.name, program_path(student.program) %></td>
            <td class="px-6 py-4 text-center"><%= student.sle %></td>
            <td class="px-6 py-4 text-center"><%= student.phone %></td>
            <td class="px-6 py-4 text-center"><%= student.attempt_number %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
   </div>
 </div>

<% end %>
<% end %>

app/views/hesis/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl mb-5 origin-center">Hesi Schedule</h1>
    <%= link_to 'New Student', new_student_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="hesis" class="min-w-full">
    <%= render partial: 'future_hesis' %>
  </div>
</div>

app/views/hesis/past_hesis.html.erb
<% Hesi.past_hesi_dates.each do |date| %>
  <h1><strong><%= "#{Hesi.day_of_week(date)}, #{ Hesi.date(date) }" %></strong></h1>
  <% Hesi.times_for_day[Hesi.day_of_week(date)].each do |time| %>
    <div class="relative flex h-16 items-center justify-between">
    <h2 class="inline-flex items-center justify-center "><strong><%= time %></strong></h2>
    <h3 class="clear-right"><%= Hesi.student_count(date, time) %></h3>
    </div>
<div class="flex flex-col">
    <div class="pb-10">
      <table class="relative w-full border">
        <thead>
          <tr>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Student name</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Advisor</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Program</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Wonderlic Score</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">phone number</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Attempt Number</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300"></th>
          </tr>
        </thead>
        <tbody class="divide-y bg-blue-100">

        <% Hesi.testers_for_date_and_time(date, Hesi.test_times[time]).each do |student| %>
          <tr>
            <td class="px-6 py-4 text-center"><%= link_to student.name, student_path(student) %></td>
            <td class="px-6 py-4 text-center"><%= link_to student.advisor.name, advisor_path(student.advisor) %> </td>
            <td class="px-6 py-4 text-center"><%= link_to student.program.name, program_path(student.program) %></td>
            <td class="px-6 py-4 text-center"><%= student.sle %></td>
            <td class="px-6 py-4 text-center"><%= student.phone %></td>
            <td class="px-6 py-4 text-center"><%= student.attempt_number %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
   </div>
 </div>

<% end %>
<% end %>

app/views/hesis/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @hesi %>

    <%= link_to 'Edit this hesi', edit_hesi_path(@hesi), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this hesi', hesi_path(@hesi), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to hesis', hesis_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>