config/routes.rb
Rails.application.routes.draw do
  resources :hesis
  devise_for :users
  resources :students
  resources :advisors
  resources :programs

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root :to => "hesis#index"
end

app/models/program.rb
class Program < ApplicationRecord
  has_many :students
  enum start_date: {
    'Nov 28th, 2022'        => 0,
    'Feb 13th, 2023'        => 1,
    'April 24th, 2023'      => 2,
    'July 3rd, 2023'        => 3,
    'Aug 28th, 2023(PN-EW)' => 4,
    'Sept 18th, 2023'       => 5,
    'Nov 27th, 2023'        => 6
  }

  def full_name
    {"DH" => "Dental Hygiene",
    "BSN" => "Bachelors of Science-Nursing",
    "PN" => "Practical Nursing",
    "PN-EW" => "Practical Nursing-Evening&Weekend",
    "DMS" => "Diagnostic Medical Sonography",
    "CVS" => "Cardiovascular Sonography",
    "PTA" => "Physical Therapy Assisting",
    "RT" => "Respiratory Therapy",
    "ST" => "Surgical Technology"}[self.name]
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: %i[ show edit update destroy ]

  # GET /programs or /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1 or /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
    @program.students.build
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs or /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to program_url(@program), notice: "Program was successfully created." }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1 or /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to program_url(@program), notice: "Program was successfully updated." }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1 or /programs/1.json
  def destroy
    @program.destroy

    respond_to do |format|
      format.html { redirect_to programs_url, notice: "Program was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def program_params
      params.require(:program).permit(:name, :minimum_sle, :minimum_hesi, :minimum_hesi_section)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_with(model: program, class: "contents") do |form| %>
  <% if program.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
        <% program.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :minimum_sle %>
    <%= form.number_field :minimum_sle, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :minimum_hesi %>
    <%= form.number_field :minimum_hesi, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :minimum_hesi_section %>
    <%= form.number_field :minimum_hesi_section, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/programs/_program.html.erb
<div id="<%= dom_id program %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= program.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Minimum sle:</strong>
    <%= program.minimum_sle %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Minimum hesi:</strong>
    <%= program.minimum_hesi %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Minimum hesi section:</strong>
    <%= program.minimum_hesi_section %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this program", program, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this program', edit_program_path(program), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/programs/_programs.html.erb
<!-- component --> 

<div class="flex flex-col h-screen">
    <div class="flex-grow overflow-auto">
      <table class="relative w-full border">
        <thead>
          <tr>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-600">Program
              name</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-600">Minimum SLE Score</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-600">Minimum Hesi Score</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-600">Minimum Hesi Sectional Score</th>
          
          </tr>
        </thead>
        <tbody class="divide-y bg-blue-100">

  <% @programs.each do |program| %>
          <tr>
            <td><%= link_to program.name, program_path(program), class: "px-6 py-4 text-center" %></td>
            <td class="px-6 py-4 text-center"><%= program.minimum_sle %></td>
            <td class="px-6 py-4 text-center"><%= program.minimum_hesi %></td>
            <td class="px-6 py-4 text-center"><%= program.minimum_hesi_section %></td> </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/programs/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing program</h1>

  <%= render "form", program: @program %>

  <%= link_to "Show this program", @program, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to programs", programs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/programs/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Programs</h1>
    <%= link_to 'New program', new_program_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="programs" class="min-w-full">
    <%= render partial: 'programs' %>
  </div>
</div>

app/views/programs/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New program</h1>

  <%= render "form", program: @program %>

  <%= link_to 'Back to programs', programs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/programs/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @program %>

    <div class="flex flex-col h-screen">
    <div class="flex-grow overflow-auto">
      <table class="relative w-full border">
        <thead>
          <tr>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Student name</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Wonderlic Score</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Phone Number</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Hesi Date</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Hesi Time</th>
          </tr>
        </thead>
        <tbody class="divide-y bg-blue-100">

 <% @program.students.sort.each do |student| %> 
          <tr>
            <td class="px-6 py-4 text-center"><%= link_to student.name, student_path %></td>
            <td class="px-6 py-4 text-center"><%= student.sle %></td>
            <td class="px-6 py-4 text-center"><%= student.phone %></td>
            <td class="px-6 py-4 text-center"><%= student.hesi_date %></td>
            <td class="px-6 py-4 text-center"><%= Hesi.test_times.keys[student.hesi_time] %></td>

   
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    </div>
  </div>

    <%= link_to 'Edit this program', edit_program_path(@program), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this program', program_path(@program), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to programs', programs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>