config/routes.rb
Rails.application.routes.draw do
  resources :hesis
  devise_for :users
  resources :students
  resources :advisors
  resources :programs

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root :to => "hesis#index"
end

app/models/advisor.rb
class Advisor < ApplicationRecord
  has_many :students
end

app/controllers/advisors_controller.rb
class AdvisorsController < ApplicationController
  before_action :set_advisor, only: %i[ show edit update destroy ]
  # before_action :order_students, only:  :show

  # GET /advisors or /advisors.json
  def index
    @advisors = Advisor.all
  end

  # GET /advisors/1 or /advisors/1.json
  def show
  end

  # GET /advisors/new
  def new
    @advisor = Advisor.new
    @advisor.students.build
  end

  # GET /advisors/1/edit
  def edit
  end

  # POST /advisors or /advisors.json
  def create
    @advisor = Advisor.new(advisor_params)

    respond_to do |format|
      if @advisor.save
        format.html { redirect_to advisor_url(@advisor), notice: "Advisor was successfully created." }
        format.json { render :show, status: :created, location: @advisor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advisors/1 or /advisors/1.json
  def update
    respond_to do |format|
      if @advisor.update(advisor_params)
        format.html { redirect_to advisor_url(@advisor), notice: "Advisor was successfully updated." }
        format.json { render :show, status: :ok, location: @advisor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advisors/1 or /advisors/1.json
  def destroy
    @advisor.destroy

    respond_to do |format|
      format.html { redirect_to advisors_url, notice: "Advisor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advisor
      @advisor = Advisor.find(params[:id])
    end

    def order_students
      self.students.order(:hesi_date)
    end
    # Only allow a list of trusted parameters through.
    def advisor_params
      params.require(:advisor).permit(:name, :email, :invitation_code)
    end
end

app/helpers/advisors_helper.rb
module AdvisorsHelper
end

app/views/advisors/_advisor.html.erb
<div id="<%= dom_id advisor %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= advisor.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= advisor.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Invitation code:</strong>
    <%= advisor.invitation_code %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this advisor", advisor, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this advisor', edit_advisor_path(advisor), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/advisors/_advisors.html.erb
<div class="flex flex-col h-screen">
    <div class="flex-grow overflow-auto">
      <table class="relative w-full border">
        <thead>
          <tr>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Name</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Email</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Invitation Code</th>
          
          </tr>
        </thead>
        <tbody class="divide-y bg-blue-100">

  <% @advisors.each do |advisor| %>
          <tr>
            <td class="px-6 py-4 text-center"><%= link_to advisor.name, advisor_path(advisor.id) %></td>
            <td class="px-6 py-4 text-center"><%= advisor.email %></td>
            <td class="px-6 py-4 text-center"><%= advisor.invitation_code %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/advisors/_form.html.erb
<%= form_with(model: advisor, class: "contents") do |form| %>
  <% if advisor.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(advisor.errors.count, "error") %> prohibited this advisor from being saved:</h2>

      <ul>
        <% advisor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :invitation_code %>
    <%= form.number_field :invitation_code, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/advisors/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing advisor</h1>

  <%= render "form", advisor: @advisor %>

  <%= link_to "Show this advisor", @advisor, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to advisors", advisors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/advisors/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Advisors</h1>
    <%= link_to 'New advisor', new_advisor_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="advisors" class="min-w-full">
    <%= render partial: 'advisors' %>
  </div>
</div>

app/views/advisors/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New advisor</h1>

  <%= render "form", advisor: @advisor %>

  <%= link_to 'Back to advisors', advisors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/advisors/show.html.erb
<div class="mx-auto  w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @advisor %>

<div class="flex flex-col h-screen">
    <div class="flex-grow overflow-auto">
      <table class="relative w-full border">
        <%= link_to %>
        <thead>
          <tr>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Student name</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Program</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Wonderlic Score</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Phone Number</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Hesi Date</th>
            <th class="sticky top-0 px-6 py-3 text-white bg-blue-300">Hesi Time</th>
          </tr>
        </thead>
        <tbody class="divide-y bg-blue-100">

 <% @advisor.students.sort.each do |student| %> 
          <tr>
            <td class="px-6 py-4 text-center"><%= link_to student.name, student_path %></td>
            <td class="px-6 py-4 text-center"><%= student.program.name %></td>
            <td class="px-6 py-4 text-center"><%= student.sle %></td>
            <td class="px-6 py-4 text-center"><%= student.phone %></td>
            <td class="px-6 py-4 text-center"><%= student.hesi_date %></td>
            <td class="px-6 py-4 text-center"><%= Hesi.test_times.keys[student.hesi_time] %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    </div>
  </div>

    <div class="inline-block ml-2">
    <%= link_to 'Edit this advisor', edit_advisor_path(@advisor), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this advisor', advisor_path(@advisor), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to advisors', advisors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>